name: Build luci-app-passwall2 (24.10 rc7 / ipq807x aarch64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (empty)
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc g++ make git wget curl unzip \
            python3 gawk libncurses-dev zlib1g-dev libssl-dev rsync file time \
            subversion zstd

      # 🔴 لینک درست SDK برای ipq807x
      - name: Download OpenWrt SDK (24.10.0-rc7 / qualcomm ipq807x)
        run: |
          mkdir -p $GITHUB_WORKSPACE/sdk && cd $GITHUB_WORKSPACE/sdk
          wget https://downloads.openwrt.org/releases/24.10.0-rc7/targets/qualcomm/ipq807x/openwrt-sdk-24.10.0-rc7-qualcomm-ipq807x_gcc-13.3.0_musl.Linux-x86_64.tar.zst
          tar --use-compress-program=unzstd -xf openwrt-sdk-24.10.0-rc7-qualcomm-ipq807x_gcc-13.3.0_musl.Linux-x86_64.tar.zst
          echo "SDK_DIR=$(ls -d openwrt-sdk-24.10.0-rc7-qualcomm-ipq807x_* )" >> $GITHUB_ENV

      - name: Prepare feeds
        run: |
          cd "$SDK_DIR"
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Add passwall2 sources
        run: |
          cd "$SDK_DIR"
          git clone https://github.com/xiaorouji/openwrt-passwall2.git package/passwall2

      # برای خطای po2lmo/host-tools
      - name: Build LuCI host tools
        run: |
          cd "$SDK_DIR"
          make package/luci-base/host/compile V=s

      - name: Build luci-app-passwall2
        run: |
          cd "$SDK_DIR"
          make package/passwall2/luci-app-passwall2/compile -j$(nproc) V=s

      - name: Collect ipk
        run: |
          cd "$SDK_DIR"
          mkdir -p $GITHUB_WORKSPACE/out
          find bin -name "luci-app-passwall2_*.ipk" -exec cp {} $GITHUB_WORKSPACE/out/ \; || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: passwall2-ipk
          path: out/
